###订单服务的端口号
server:
  port: 9000
###服务别名----服务注册到注册中心名称
spring:
  application:
    name: order
  cloud:
    client:
      ipAddress: 192.168.116.11
eureka:
  client:
    service-url:
      ##### 当前会员服务注册到eureka服务地址
      #      defaultZone: http://localhost:8100/eureka,http://localhost:9100/eureka
      defaultZone: http://localhost:7000/eureka
    ### 需要将我的服务注册到eureka上
    register-with-eureka: true
    ####需要检索服务
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 2
    ####设置hostName
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

###设置feign客户端超时时间
ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

#### hystrix禁止服务超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

swagger:
  base-package: com.controllers